{{ config(
    materialized='table',
    schema='_03_GOLD'
) }}

SELECT

ROUND(AVG(DISTANCE_KM), 2) AS AVG_STATION_DISTANCE_KM,
ROUND(MIN(DISTANCE_KM), 2) AS CLOSEST_STATION_DISTANCE_KM,
ROUND(MAX(DISTANCE_KM), 2) AS FURTHEST_STATION_DISTANCE_KM

FROM {{ source('reference','STATION_DISTANCES_KM') }}