USE DATABASE DEV_EV_ANALYTICS

CREATE OR REPLACE SECRET GIT_SECRET
TYPE=PASSWORD
USERNAME='sularaperera'
PASSWORD='<YOUR GIT TOKEN>';

CREATE OR REPLACE API INTEGRATION GIT_INT
API_PROVIDER = git_https_api
API_ALLOWED_PREFIXES = ('https://github.com/sularaperera/')
ENABLED = TRUE
ALLOWED_AUTHENTICATION_SECRETS = (GIT_SECRET);
