USE DATABASE DEV_EV_ANALYTICS

CREATE OR REPLACE SECRET GIT_SECRET
TYPE=PASSWORD
USERNAME='sularaperera'
PASSWORD='eyJraWQiOiI4MjcwODE4NTIyODkwMzAiLCJhbGciOiJFUzI1NiJ9.eyJwIjoiNDkyOTc5MjQ6NDkyOTc5MjQiLCJpc3MiOiJTRjoyMDAzIiwiZXhwIjoxNzc0NjM5MTM5fQ.0DiB-12FCbT7XrxeD0IVETVF8O1KJkUo9UDjNYoV9rlDcMe4YqUtTMj584g8CevtblWaaAox0_GRQ3BLJlHaJw';

CREATE OR REPLACE API INTEGRATION GIT_INT
API_PROVIDER = git_https_api
API_ALLOWED_PREFIXES = ('https://github.com/sularaperera/')
ENABLED = TRUE
ALLOWED_AUTHENTICATION_SECRETS = (GIT_SECRET);