CREATE OR REPLACE TABLE DEV_EV_ANALYTICS._99_REFERENCE.POPULATION_BY_REGION (
    REGION               VARCHAR,
    POPULATION         VARCHAR
);


COPY INTO DEV_EV_ANALYTICS._99_REFERENCE.POPULATION_BY_REGION
FROM @"DEV_EV_ANALYTICS"."_00_STAGING"."EV_CSV_STAGE"/Population_by_Region_Cleaned.csv
FILE_FORMAT = (FORMAT_NAME = 'DEV_EV_ANALYTICS._99_REFERENCE.csv_format')
ON_ERROR = 'CONTINUE';