CREATE OR REPLACE TABLE DEV_EV_ANALYTICS._99_REFERENCE.TLA_TO_REGION (
    TLA               VARCHAR,
    TLA_CLEANED       VARCHAR,
    REGION            VARCHAR
);


COPY INTO DEV_EV_ANALYTICS._99_REFERENCE.TLA_TO_REGION
FROM @"DEV_EV_ANALYTICS"."_00_STAGING"."EV_CSV_STAGE"/TLA_to_Region.csv
FILE_FORMAT = (
    FORMAT_NAME = 'DEV_EV_ANALYTICS._99_REFERENCE.csv_format'
    ENCODING = 'UTF8'
    )
ON_ERROR = 'CONTINUE';